language: node_js
node_js:
  - 0.11
  - 0.10
deploy:
  provider: npm
  email: "keichi.t@me.com"
  api_key: "muA6TxOZbjapHheycs6wwPbHGH3Wez6yp84CX9kBy79LrrxTCdfLt9o0Q3wg9wkT5yMFiler4EDmokknZ/qObNYOGG4NreZDx5N4IA2B6QE4Z53gtGbxsOY1CL3JZSOgg447KQGWLTk/5yqtWvLr0wM2YlAFjPG2wViiYrDLwWY="
  on:
    branch: master
    tags: true
